### ISSUE TITLE
[BUG] web trainer requires TensorFlow version >= 2.12

### ISSUE THREAD

**Issue by eizenman** [magenta/ddsp-vst#48]
**Describe the bug**
The colab web trainer errors when it starts training

`
Training...
2023-08-07 08:10:28.967989: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.10/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-08-07 08:10:28.968103: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.10/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-08-07 08:10:28.968122: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/usr/local/bin/ddsp_run", line 5, in <module>
    from ddsp.training.ddsp_run import console_entry_point
  File "/usr/local/lib/python3.10/dist-packages/ddsp/__init__.py", line 21, in <module>
    from ddsp import losses
  File "/usr/local/lib/python3.10/dist-packages/ddsp/losses.py", line 23, in <module>
    from ddsp import spectral_ops
  File "/usr/local/lib/python3.10/dist-packages/ddsp/spectral_ops.py", line 25, in <module>
    import tensorflow_probability as tfp
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/__init__.py", line 20, in <module>
    from tensorflow_probability import substrates
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/substrates/__init__.py", line 17, in <module>
    from tensorflow_probability.python.internal import all_util
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/__init__.py", line 138, in <module>
    dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/internal/lazy_loader.py", line 57, in __dir__
    module = self._load()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/internal/lazy_loader.py", line 37, in _load
    self._on_first_access()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/__init__.py", line 59, in _validate_tf_environment
    raise ImportError(
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.12; Detected an installation of version 2.11.1. Please upgrade TensorFlow to proceed.
`

**System Info**
- Macbook Air 2020, M1 Silicon, Monterey
- Runtime type set to T4 GPU

**To Reproduce**
Run the [web trainer](https://colab.research.google.com/github/magenta/ddsp/blob/main/ddsp/colab/demos/Train_VST.ipynb)

**Additional context**
I tried to add the following but it errors some other issues
!pip install tensorflow==2.12

**Comment by dimok135** [comment]
Hi. I get the same error. Nothing helps :(

**Comment by dimok135** [comment]
After a week of pain I found a working solution!!! Run these lines of code before training to downgrade the libraries.

!pip uninstall -y keras tensorflow tensorflow-probability absl-py astunparse flatbuffers gast google-pasta grpcio h5py keras keras-preprocessing libclang numpy opt-einsum protobuf setuptools six tensorboard tensorflow-io-gcs-filesystem termcolor tf-estimator-nightly typing-extensions wrapt
!pip install --disable-pip-version-check --no-cache-dir tensorflow==2.11.0
!pip install tensorflow-probability==0.15.0
!pip install keras==2.11.0

**Comment by eizenman** [comment]
Thanks @dimok135 , that works
